### ISSUE TITLE
[doc issue] abapGit missing in "Open Source Legal Notices"

### ISSUE THREAD

**Issue by mbtools** [SAP-docs/abap-platform-trial-image#16]
### Issue description

Over 500 open source packages are listed but abapGit is missing 

https://support.sap.com/content/dam/launchpad/en_us/osln/osln/73554900100900008093_20240117061308.pdf

Please add it

### Feedback Type (Optional)

content gaps

**Comment by KiraMila** [comment]
Sorry for the delay. I will take care!
Stephan/SAP

**Comment by mbtools** [comment]
Thanks for the quick resolution :-)

PS: It's an old URL (redirect). The correct one is https://github.com/abapGit/abapGit

**Comment by KiraMila** [comment]
>PS: It's an old URL (redirect). The correct one is https://github.com/abapGit/abapGit
A change at this point would have resulted in a new FOSS component, which would have taken MUCH more time... ;) If you could live with that we should let it this way... ;)

**Comment by mbtools** [comment]
np
